# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#     * Rearrange models' order
#     * Make sure each model has one field with primary_key=True
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [appname]'
# into your database.
from __future__ import unicode_literals

from django.db import models

class AggregatedEventReport(models.Model):
    dever_id = models.IntegerField(null=True, blank=True)
    media_id = models.IntegerField(null=True, blank=True)
    sponsor_id = models.IntegerField(null=True, blank=True)
    ad_plan_id = models.IntegerField(null=True, blank=True)
    ad_strategy_id = models.IntegerField(null=True, blank=True)
    ad_creative_id = models.IntegerField(null=True, blank=True)
    ad_placement_type = models.IntegerField(null=True, blank=True)
    cost_type = models.IntegerField(null=True, blank=True)
    report_type = models.IntegerField(null=True, blank=True)
    publish_id = models.CharField(max_length=128L, blank=True)
    origin = models.CharField(max_length=8L, blank=True)
    action_type = models.CharField(max_length=32L, blank=True)
    action_count = models.IntegerField(null=True, blank=True)
    pkg = models.CharField(max_length=128L, blank=True)
    vc = models.CharField(max_length=32L, blank=True)
    vn = models.CharField(max_length=32L, blank=True)
    sv = models.IntegerField(null=True, blank=True)
    use_time = models.DateTimeField(null=True, blank=True)
    class Meta:
        db_table = 'aggregated_event_report'

class ClickActivation(models.Model):
    searchid = models.BigIntegerField(null=True, blank=True)
    mediaid = models.IntegerField(null=True, blank=True)
    adcreativeid = models.IntegerField(null=True, blank=True)
    imp_deverid = models.IntegerField(null=True, blank=True)
    imp_impressiontime = models.BigIntegerField(null=True, blank=True)
    imp_sponsorid = models.IntegerField(null=True, blank=True)
    imp_adplanid = models.IntegerField(null=True, blank=True)
    imp_adstrategyid = models.IntegerField(null=True, blank=True)
    imp_adproperty = models.IntegerField(null=True, blank=True)
    imp_density = models.FloatField(null=True, blank=True)
    imp_bid = models.BigIntegerField(null=True, blank=True)
    imp_clickprice = models.BigIntegerField(null=True, blank=True)
    imp_impressionprice = models.BigIntegerField(null=True, blank=True)
    imp_adexpcategory = models.IntegerField(null=True, blank=True)
    imp_adctr = models.FloatField(null=True, blank=True)
    imp_costtype = models.IntegerField(null=True, blank=True)
    imp_adkeyword = models.CharField(max_length=255L, blank=True)
    imp_adtype = models.IntegerField(null=True, blank=True)
    imp_ischarge = models.IntegerField(null=True, blank=True)
    imp_adprint = models.CharField(max_length=255L, blank=True)
    imp_landingurl = models.CharField(max_length=255L, blank=True)
    imp_expid = models.IntegerField(null=True, blank=True)
    imp_ip = models.BigIntegerField(null=True, blank=True)
    imp_carrier = models.IntegerField(null=True, blank=True)
    imp_refer = models.CharField(max_length=255L, blank=True)
    imp_device = models.IntegerField(null=True, blank=True)
    imp_os = models.IntegerField(null=True, blank=True)
    imp_imei = models.BigIntegerField(null=True, blank=True)
    imp_imsi = models.BigIntegerField(null=True, blank=True)
    imp_cookieid = models.CharField(max_length=255L, blank=True)
    imp_publishid = models.CharField(max_length=255L, blank=True)
    imp_uuid = models.CharField(max_length=255L, blank=True)
    imp_mediatype = models.IntegerField(null=True, blank=True)
    imp_region = models.IntegerField(null=True, blank=True)
    imp_spot = models.CharField(max_length=255L, blank=True)
    imp_sdktype = models.IntegerField(null=True, blank=True)
    imp_sdkversion = models.CharField(max_length=255L, blank=True)
    imp_clientencoding = models.IntegerField(null=True, blank=True)
    imp_screenisvertical = models.IntegerField(null=True, blank=True)
    imp_screenwidth = models.IntegerField(null=True, blank=True)
    imp_screenheight = models.IntegerField(null=True, blank=True)
    imp_screendensity = models.FloatField(null=True, blank=True)
    imp_mediakeyword = models.CharField(max_length=255L, blank=True)
    imp_mediasearchquery = models.CharField(max_length=255L, blank=True)
    imp_appname = models.CharField(max_length=255L, blank=True)
    imp_appversion = models.CharField(max_length=255L, blank=True)
    imp_coordtime = models.BigIntegerField(null=True, blank=True)
    imp_latitude = models.FloatField(null=True, blank=True)
    imp_longitude = models.FloatField(null=True, blank=True)
    imp_postalcode = models.IntegerField(null=True, blank=True)
    imp_birthday = models.IntegerField(null=True, blank=True)
    imp_gender = models.IntegerField(null=True, blank=True)
    imp_accesstype = models.IntegerField(null=True, blank=True)
    imp_url = models.CharField(max_length=255L, blank=True)
    imp_determine = models.CharField(max_length=255L, blank=True)
    imp_osdevice_dependency = models.CharField(max_length=255L, blank=True)
    imp_xheader = models.CharField(max_length=255L, blank=True)
    imp_browser_id = models.IntegerField(null=True, blank=True)
    imp_browser_version = models.CharField(max_length=255L, blank=True)
    imp_spamtype = models.CharField(max_length=255L, blank=True)
    imp_extinfo = models.CharField(max_length=255L, blank=True)
    imp_pb_name = models.CharField(max_length=255L, blank=True)
    imp_lpkg = models.CharField(max_length=255L, blank=True)
    imp_sv = models.IntegerField(null=True, blank=True)
    imp_sdk_platform = models.IntegerField(null=True, blank=True)
    imp_region_code = models.IntegerField(null=True, blank=True)
    imp_device_dispname = models.CharField(max_length=255L, blank=True)
    imp_mediaprice = models.BigIntegerField(null=True, blank=True)
    imp_isv = models.IntegerField(null=True, blank=True)
    imp_isspam = models.IntegerField(null=True, blank=True)
    clk_impressiontime = models.BigIntegerField(null=True, blank=True)
    clk_clicktime = models.BigIntegerField(null=True, blank=True)
    clk_deverid = models.IntegerField(null=True, blank=True)
    clk_sponsorid = models.IntegerField(null=True, blank=True)
    clk_adplanid = models.IntegerField(null=True, blank=True)
    clk_adstrategyid = models.IntegerField(null=True, blank=True)
    clk_bid = models.BigIntegerField(null=True, blank=True)
    clk_price = models.BigIntegerField(null=True, blank=True)
    clk_costtype = models.IntegerField(null=True, blank=True)
    clk_clk_ischarge = models.IntegerField(null=True, blank=True)
    clk_landingurl = models.CharField(max_length=1000L, db_column='clK_landingurl', blank=True) # Field name made lowercase.
    clk_remoteaddrclk = models.BigIntegerField(null=True, blank=True)
    clk_refererclk = models.CharField(max_length=255L, blank=True)
    clk_cookieclk = models.CharField(max_length=255L, blank=True)
    clk_expid = models.IntegerField(null=True, blank=True)
    clk_ip = models.BigIntegerField(null=True, blank=True)
    clk_carrier = models.IntegerField(null=True, blank=True)
    clk_useragent = models.CharField(max_length=255L, blank=True)
    clk_refer = models.CharField(max_length=255L, blank=True)
    clk_device = models.IntegerField(null=True, blank=True)
    clk_os = models.IntegerField(null=True, blank=True)
    clk_imei = models.BigIntegerField(null=True, blank=True)
    clk_imsi = models.BigIntegerField(null=True, blank=True)
    clk_cookieid = models.CharField(max_length=255L, blank=True)
    clk_publishid = models.CharField(max_length=255L, blank=True)
    clk_uuid = models.CharField(max_length=255L, blank=True)
    clk_redirecttype = models.IntegerField(null=True, blank=True)
    clk_region = models.IntegerField(null=True, blank=True)
    clk_spot = models.CharField(max_length=255L, blank=True)
    clk_mediatype = models.IntegerField(null=True, blank=True)
    clk_track = models.CharField(max_length=255L, blank=True)
    clk_spamtype = models.CharField(max_length=255L, blank=True)
    clk_extinfo = models.CharField(max_length=255L, blank=True)
    clk_sharerate = models.IntegerField(null=True, blank=True)
    clk_mediaprice = models.BigIntegerField(null=True, blank=True)
    clk_isspam = models.IntegerField(null=True, blank=True)
    acs_impressiontime = models.BigIntegerField(null=True, blank=True)
    acs_uri = models.CharField(max_length=255L, blank=True)
    fin_settledprice = models.BigIntegerField(null=True, blank=True)
    fin_settledmediashare = models.BigIntegerField(null=True, blank=True)
    imp_guid = models.CharField(max_length=255L, blank=True)
    is_click = models.IntegerField(null=True, blank=True)
    is_arrive = models.IntegerField(null=True, blank=True)
    is_download = models.IntegerField(null=True, blank=True)
    imp_devicemacaddrsign = models.CharField(max_length=255L, blank=True)
    imp_alternative_dims = models.CharField(max_length=255L, blank=True)
    imp_adplacementtype = models.IntegerField(null=True, blank=True)
    imp_ducookie = models.CharField(max_length=255L, blank=True)
    imp_duid = models.CharField(max_length=255L, blank=True)
    imp_devicejailbreak = models.IntegerField(null=True, blank=True)
    imp_originalimei = models.CharField(max_length=255L, blank=True)
    clk_duid = models.CharField(max_length=255L, blank=True)
    is_activation = models.IntegerField(null=True, blank=True)
    act_time = models.BigIntegerField(null=True, blank=True)
    act_load_id = models.CharField(max_length=255L, blank=True)
    act_device_id = models.CharField(max_length=255L, blank=True)
    act_device_id_type = models.CharField(max_length=255L, blank=True)
    act_source = models.IntegerField(null=True, blank=True)
    act_sponsor_id = models.IntegerField(null=True, blank=True)
    act_package_name = models.CharField(max_length=255L, blank=True)
    act_package_version = models.CharField(max_length=255L, blank=True)
    act_package_version_code = models.IntegerField(null=True, blank=True)
    act_duid = models.CharField(max_length=255L, blank=True)
    dt = models.IntegerField(null=True, blank=True)
    hr = models.CharField(max_length=2L, blank=True)
    class Meta:
        db_table = 'click_activation'

class ClickSummary(models.Model):
    mediaid = models.IntegerField(null=True, blank=True)
    costtype = models.IntegerField(null=True, blank=True)
    sdk_platform = models.IntegerField(null=True, blank=True)
    sv = models.IntegerField(null=True, blank=True)
    adplacementtype = models.IntegerField(null=True, blank=True)
    os = models.IntegerField(null=True, blank=True)
    adcreativeid = models.IntegerField(null=True, blank=True)
    click = models.IntegerField(null=True, blank=True)
    lclick = models.IntegerField(null=True, blank=True)
    dt = models.DateField(null=True, blank=True)
    hr = models.IntegerField(null=True, blank=True)
    eclick = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = 'click_summary'

class ClkHourly(models.Model):
    searchid = models.BigIntegerField(null=True, blank=True)
    impressiontime = models.BigIntegerField(null=True, blank=True)
    clicktime = models.BigIntegerField(null=True, blank=True)
    deverid = models.IntegerField(null=True, blank=True)
    mediaid = models.IntegerField(null=True, blank=True)
    sponsorid = models.IntegerField(null=True, blank=True)
    adplanid = models.IntegerField(null=True, blank=True)
    adstrategyid = models.IntegerField(null=True, blank=True)
    adcreativeid = models.IntegerField(null=True, blank=True)
    bid = models.BigIntegerField(null=True, blank=True)
    price = models.BigIntegerField(null=True, blank=True)
    costtype = models.IntegerField(null=True, blank=True)
    ischarge = models.IntegerField(null=True, blank=True)
    landingurl = models.CharField(max_length=1000L, blank=True)
    useragentclk = models.CharField(max_length=1000L, blank=True)
    remoteaddrclk = models.BigIntegerField(null=True, blank=True)
    refererclk = models.CharField(max_length=6000L, blank=True)
    cookieclk = models.CharField(max_length=255L, blank=True)
    expid = models.IntegerField(null=True, blank=True)
    ip = models.BigIntegerField(null=True, blank=True)
    carrier = models.IntegerField(null=True, blank=True)
    useragent = models.CharField(max_length=255L, blank=True)
    refer = models.CharField(max_length=255L, blank=True)
    device = models.IntegerField(null=True, blank=True)
    os = models.IntegerField(null=True, blank=True)
    imei = models.BigIntegerField(null=True, blank=True)
    imsi = models.BigIntegerField(null=True, blank=True)
    cookieid = models.CharField(max_length=255L, blank=True)
    publishid = models.CharField(max_length=255L, blank=True)
    uuid = models.CharField(max_length=255L, blank=True)
    redirecttype = models.IntegerField(null=True, blank=True)
    region = models.IntegerField(null=True, blank=True)
    spot = models.CharField(max_length=255L, blank=True)
    mediatype = models.IntegerField(null=True, blank=True)
    track = models.CharField(max_length=255L, blank=True)
    spamtype = models.CharField(max_length=255L, blank=True)
    extinfo = models.CharField(max_length=255L, blank=True)
    sharerate = models.IntegerField(null=True, blank=True)
    mediaprice = models.BigIntegerField(null=True, blank=True)
    isspam = models.IntegerField(null=True, blank=True)
    guid = models.CharField(max_length=255L, blank=True)
    region_code = models.IntegerField(null=True, blank=True)
    accesstype = models.IntegerField(null=True, blank=True)
    adplacementtype = models.IntegerField(null=True, blank=True)
    devicemacaddrsign = models.CharField(max_length=255L, blank=True)
    duid = models.CharField(max_length=255L, blank=True)
    dt = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = 'clk_hourly'

class EventReport(models.Model):
    search_id = models.BigIntegerField(null=True, blank=True)
    impression_time = models.BigIntegerField(null=True, blank=True)
    report_time = models.BigIntegerField(null=True, blank=True)
    dever_id = models.IntegerField(null=True, blank=True)
    media_id = models.IntegerField(null=True, blank=True)
    sponsor_id = models.IntegerField(null=True, blank=True)
    ad_plan_id = models.IntegerField(null=True, blank=True)
    ad_strategy_id = models.IntegerField(null=True, blank=True)
    ad_creative_id = models.IntegerField(null=True, blank=True)
    ad_placement_type = models.IntegerField(null=True, blank=True)
    cost_type = models.IntegerField(null=True, blank=True)
    exp_id = models.IntegerField(null=True, blank=True)
    ip = models.BigIntegerField(null=True, blank=True)
    guid = models.BigIntegerField(null=True, blank=True)
    v = models.CharField(max_length=32L, blank=True)
    sv = models.IntegerField(null=True, blank=True)
    report_type = models.IntegerField(null=True, blank=True)
    ua = models.CharField(max_length=255L, blank=True)
    publish_id = models.CharField(max_length=128L, blank=True)
    idv = models.CharField(max_length=128L, blank=True)
    ts = models.BigIntegerField(null=True, blank=True)
    device_mac_addr_sign = models.CharField(max_length=32L, blank=True)
    origin = models.CharField(max_length=8L, blank=True)
    action_type = models.CharField(max_length=32L, blank=True)
    pkg = models.CharField(max_length=128L, blank=True)
    vc = models.CharField(max_length=32L, blank=True)
    vn = models.CharField(max_length=32L, blank=True)
    failsafe = models.CharField(max_length=255L, blank=True)
    ext_data = models.CharField(max_length=255L, blank=True)
    dt = models.CharField(max_length=8L, blank=True)
    hr = models.CharField(max_length=2L, blank=True)
    use_time = models.DateTimeField(null=True, blank=True)
    class Meta:
        db_table = 'event_report'

class EventReportSdk3X(models.Model):
    dever_id = models.IntegerField(null=True, blank=True)
    media_id = models.IntegerField(null=True, blank=True)
    sponsor_id = models.IntegerField(null=True, blank=True)
    ad_plan_id = models.IntegerField(null=True, blank=True)
    ad_strategy_id = models.IntegerField(null=True, blank=True)
    ad_creative_id = models.IntegerField(null=True, blank=True)
    ad_placement_type = models.IntegerField(null=True, blank=True)
    cost_type = models.IntegerField(null=True, blank=True)
    report_type = models.IntegerField(null=True, blank=True)
    publish_id = models.CharField(max_length=128L, blank=True)
    origin = models.CharField(max_length=8L, blank=True)
    action_type = models.CharField(max_length=32L, blank=True)
    action_count = models.IntegerField(null=True, blank=True)
    pkg = models.CharField(max_length=128L, blank=True)
    vc = models.CharField(max_length=32L, blank=True)
    vn = models.CharField(max_length=32L, blank=True)
    sv = models.IntegerField(null=True, blank=True)
    use_time = models.DateTimeField(null=True, blank=True)
    dt = models.DateField(null=True, blank=True)
    hr = models.IntegerField(null=True, blank=True)
    media_type = models.IntegerField(null=True, blank=True)
    sdk_type = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = 'event_report_sdk3x'

class IcaHourly(models.Model):
    searchid = models.BigIntegerField(null=True, blank=True)
    mediaid = models.IntegerField(null=True, blank=True)
    adcreativeid = models.IntegerField(null=True, blank=True)
    imp_deverid = models.IntegerField(null=True, blank=True)
    imp_impressiontime = models.BigIntegerField(null=True, blank=True)
    imp_sponsorid = models.IntegerField(null=True, blank=True)
    imp_adplanid = models.IntegerField(null=True, blank=True)
    imp_adstrategyid = models.IntegerField(null=True, blank=True)
    imp_adproperty = models.IntegerField(null=True, blank=True)
    imp_density = models.FloatField(null=True, blank=True)
    imp_bid = models.BigIntegerField(null=True, blank=True)
    imp_clickprice = models.BigIntegerField(null=True, blank=True)
    imp_impressionprice = models.BigIntegerField(null=True, blank=True)
    imp_adexpcategory = models.IntegerField(null=True, blank=True)
    imp_adctr = models.FloatField(null=True, blank=True)
    imp_costtype = models.IntegerField(null=True, blank=True)
    imp_adkeyword = models.CharField(max_length=255L, blank=True)
    imp_adtype = models.IntegerField(null=True, blank=True)
    imp_ischarge = models.IntegerField(null=True, blank=True)
    imp_adprint = models.CharField(max_length=255L, blank=True)
    imp_landingurl = models.CharField(max_length=255L, blank=True)
    imp_expid = models.IntegerField(null=True, blank=True)
    imp_ip = models.BigIntegerField(null=True, blank=True)
    imp_carrier = models.IntegerField(null=True, blank=True)
    imp_useragent = models.CharField(max_length=255L, blank=True)
    imp_refer = models.CharField(max_length=255L, blank=True)
    imp_device = models.IntegerField(null=True, blank=True)
    imp_os = models.IntegerField(null=True, blank=True)
    imp_imei = models.BigIntegerField(null=True, blank=True)
    imp_imsi = models.BigIntegerField(null=True, blank=True)
    imp_cookieid = models.CharField(max_length=255L, blank=True)
    imp_publishid = models.CharField(max_length=255L, blank=True)
    imp_uuid = models.CharField(max_length=255L, blank=True)
    imp_mediatype = models.IntegerField(null=True, blank=True)
    imp_region = models.IntegerField(null=True, blank=True)
    imp_spot = models.CharField(max_length=255L, blank=True)
    imp_sdktype = models.IntegerField(null=True, blank=True)
    imp_sdkversion = models.CharField(max_length=255L, blank=True)
    imp_clientencoding = models.IntegerField(null=True, blank=True)
    imp_screenisvertical = models.IntegerField(null=True, blank=True)
    imp_screenwidth = models.IntegerField(null=True, blank=True)
    imp_screenheight = models.IntegerField(null=True, blank=True)
    imp_screendensity = models.FloatField(null=True, blank=True)
    imp_capability = models.CharField(max_length=1024L, blank=True)
    imp_mediakeyword = models.CharField(max_length=255L, blank=True)
    imp_mediasearchquery = models.CharField(max_length=255L, blank=True)
    imp_appname = models.CharField(max_length=255L, blank=True)
    imp_appversion = models.CharField(max_length=255L, blank=True)
    imp_coordtime = models.BigIntegerField(null=True, blank=True)
    imp_latitude = models.FloatField(null=True, blank=True)
    imp_longitude = models.FloatField(null=True, blank=True)
    imp_postalcode = models.IntegerField(null=True, blank=True)
    imp_birthday = models.IntegerField(null=True, blank=True)
    imp_gender = models.IntegerField(null=True, blank=True)
    imp_accesstype = models.IntegerField(null=True, blank=True)
    imp_url = models.CharField(max_length=255L, blank=True)
    imp_determine = models.CharField(max_length=255L, blank=True)
    imp_osdevice_dependency = models.CharField(max_length=255L, blank=True)
    imp_xheader = models.CharField(max_length=255L, blank=True)
    imp_browser_id = models.IntegerField(null=True, blank=True)
    imp_browser_version = models.CharField(max_length=255L, blank=True)
    imp_spamtype = models.CharField(max_length=255L, blank=True)
    imp_extinfo = models.CharField(max_length=255L, blank=True)
    imp_pb_name = models.CharField(max_length=255L, blank=True)
    imp_lpkg = models.CharField(max_length=255L, blank=True)
    imp_sv = models.IntegerField(null=True, blank=True)
    imp_sdk_platform = models.IntegerField(null=True, blank=True)
    imp_region_code = models.IntegerField(null=True, blank=True)
    imp_device_dispname = models.CharField(max_length=255L, blank=True)
    imp_mediaprice = models.BigIntegerField(null=True, blank=True)
    imp_isv = models.IntegerField(null=True, blank=True)
    imp_isspam = models.IntegerField(null=True, blank=True)
    clk_impressiontime = models.BigIntegerField(null=True, blank=True)
    clk_clicktime = models.BigIntegerField(null=True, blank=True)
    clk_deverid = models.IntegerField(null=True, blank=True)
    clk_sponsorid = models.IntegerField(null=True, blank=True)
    clk_adplanid = models.IntegerField(null=True, blank=True)
    clk_adstrategyid = models.IntegerField(null=True, blank=True)
    clk_bid = models.BigIntegerField(null=True, blank=True)
    clk_price = models.BigIntegerField(null=True, blank=True)
    clk_costtype = models.IntegerField(null=True, blank=True)
    clk_clk_ischarge = models.IntegerField(null=True, blank=True)
    clk_landingurl = models.CharField(max_length=255L, blank=True)
    clk_useragentclk = models.CharField(max_length=255L, blank=True)
    clk_remoteaddrclk = models.BigIntegerField(null=True, blank=True)
    clk_refererclk = models.CharField(max_length=255L, blank=True)
    clk_cookieclk = models.CharField(max_length=255L, blank=True)
    clk_expid = models.IntegerField(null=True, blank=True)
    clk_ip = models.BigIntegerField(null=True, blank=True)
    clk_carrier = models.IntegerField(null=True, blank=True)
    clk_useragent = models.CharField(max_length=255L, blank=True)
    clk_refer = models.CharField(max_length=255L, blank=True)
    clk_device = models.IntegerField(null=True, blank=True)
    clk_os = models.IntegerField(null=True, blank=True)
    clk_imei = models.BigIntegerField(null=True, blank=True)
    clk_imsi = models.BigIntegerField(null=True, blank=True)
    clk_cookieid = models.CharField(max_length=255L, blank=True)
    clk_publishid = models.CharField(max_length=255L, blank=True)
    clk_uuid = models.CharField(max_length=255L, blank=True)
    clk_redirecttype = models.IntegerField(null=True, blank=True)
    clk_region = models.IntegerField(null=True, blank=True)
    clk_spot = models.CharField(max_length=255L, blank=True)
    clk_mediatype = models.IntegerField(null=True, blank=True)
    clk_track = models.CharField(max_length=255L, blank=True)
    clk_spamtype = models.CharField(max_length=255L, blank=True)
    clk_extinfo = models.CharField(max_length=255L, blank=True)
    clk_sharerate = models.IntegerField(null=True, blank=True)
    clk_mediaprice = models.BigIntegerField(null=True, blank=True)
    clk_isspam = models.IntegerField(null=True, blank=True)
    acs_impressiontime = models.BigIntegerField(null=True, blank=True)
    acs_uri = models.CharField(max_length=255L, blank=True)
    fin_settledprice = models.BigIntegerField(null=True, blank=True)
    fin_settledmediashare = models.BigIntegerField(null=True, blank=True)
    imp_guid = models.CharField(max_length=255L, blank=True)
    is_click = models.IntegerField(null=True, blank=True)
    is_arrive = models.IntegerField(null=True, blank=True)
    is_download = models.IntegerField(null=True, blank=True)
    imp_devicemacaddrsign = models.CharField(max_length=255L, blank=True)
    imp_alternative_dims = models.CharField(max_length=255L, blank=True)
    imp_adplacementtype = models.IntegerField(null=True, blank=True)
    imp_ducookie = models.CharField(max_length=255L, blank=True)
    imp_duid = models.CharField(max_length=255L, blank=True)
    imp_devicejailbreak = models.IntegerField(null=True, blank=True)
    imp_originalimei = models.CharField(max_length=255L, blank=True)
    clk_duid = models.CharField(max_length=255L, blank=True)
    imp_adcreative_package_name = models.CharField(max_length=255L, blank=True)
    imp_adcreative_package_version = models.CharField(max_length=255L, blank=True)
    imp_adcreative_render_type = models.IntegerField(null=True, blank=True)
    imp_oid = models.CharField(max_length=255L, blank=True)
    imp_sdknetwork = models.CharField(max_length=255L, blank=True)
    imp_intermediary = models.CharField(max_length=255L, blank=True)
    imp_dim = models.CharField(max_length=255L, blank=True)
    imp_templatesize = models.IntegerField(null=True, blank=True)
    clk_guid = models.BigIntegerField(null=True, blank=True)
    clk_region_code = models.IntegerField(null=True, blank=True)
    clk_accesstype = models.IntegerField(null=True, blank=True)
    clk_adplacementtype = models.IntegerField(null=True, blank=True)
    clk_devicemacaddrsign = models.CharField(max_length=255L, blank=True)
    clk_sdkorigin = models.CharField(max_length=255L, blank=True)
    clk_isv = models.IntegerField(null=True, blank=True)
    is_download_finish = models.IntegerField(null=True, blank=True)
    imp_dmac = models.CharField(max_length=255L, blank=True)
    imp_amac = models.CharField(max_length=255L, blank=True)
    imp_pmid = models.IntegerField(null=True, blank=True)
    imp_ifa = models.CharField(max_length=255L, blank=True)
    imp_lat = models.CharField(max_length=255L, blank=True)
    clk_pmid = models.IntegerField(null=True, blank=True)
    clk_platform = models.IntegerField(null=True, blank=True)
    clk_realbid = models.BigIntegerField(null=True, blank=True)
    dt = models.IntegerField(null=True, blank=True)
    hr = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = 'ica_hourly'

class ImpReportSummary(models.Model):
    deverid = models.IntegerField(null=True, blank=True)
    mediaid = models.IntegerField(null=True, blank=True)
    os = models.IntegerField(null=True, blank=True)
    sponsorid = models.IntegerField(null=True, blank=True)
    adcreativeid = models.IntegerField(null=True, blank=True)
    adplacementtype = models.IntegerField(null=True, blank=True)
    costtype = models.IntegerField(null=True, blank=True)
    isspam = models.IntegerField(null=True, blank=True)
    ischarge = models.IntegerField(null=True, blank=True)
    imp_report_count = models.IntegerField(null=True, blank=True)
    sv = models.IntegerField(null=True, blank=True)
    phase = models.CharField(max_length=64L, blank=True)
    dt = models.DateField(null=True, blank=True)
    hr = models.IntegerField(null=True, blank=True)
    mediatype = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = 'imp_report_summary'

class ImpressionSummary(models.Model):
    mediaid = models.IntegerField(null=True, blank=True)
    costtype = models.IntegerField(null=True, blank=True)
    sdk_platform = models.IntegerField(null=True, blank=True)
    sv = models.IntegerField(null=True, blank=True)
    adplacementtype = models.IntegerField(null=True, blank=True)
    os = models.IntegerField(null=True, blank=True)
    adcreativeid = models.IntegerField(null=True, blank=True)
    request = models.IntegerField(null=True, blank=True)
    erequest = models.IntegerField(null=True, blank=True)
    impression = models.IntegerField(null=True, blank=True)
    eimpression = models.IntegerField(null=True, blank=True)
    dt = models.DateField(null=True, blank=True)
    hr = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = 'impression_summary'

class LandingNameIndex(models.Model):
    landing_name = models.CharField(max_length=32L, primary_key=True)
    referer = models.CharField(max_length=1024L)
    lastupdate = models.IntegerField()
    class Meta:
        db_table = 'landing_name_index'

class LandingReport(models.Model):
    id = models.BigIntegerField(primary_key=True)
    searchid = models.BigIntegerField()
    media_id = models.IntegerField()
    adcreative_id = models.IntegerField()
    adplan_id = models.IntegerField()
    adstrategy_id = models.IntegerField()
    landing_name = models.CharField(max_length=32L)
    ip = models.CharField(max_length=32L)
    request = models.CharField(max_length=2048L)
    ua = models.CharField(max_length=1024L)
    referer = models.CharField(max_length=1024L)
    xxxxxxxxtrack = models.CharField(max_length=128L)
    page = models.CharField(max_length=32L)
    monitor_time = models.BigIntegerField()
    original_param = models.CharField(max_length=2048L)
    monitor_type = models.CharField(max_length=32L)
    adsponsor_id = models.IntegerField()
    dt = models.IntegerField()
    hr = models.IntegerField()
    class Meta:
        db_table = 'landing_report'

class LandingReportNew(models.Model):
    id = models.BigIntegerField(primary_key=True)
    searchid = models.BigIntegerField()
    media_id = models.IntegerField()
    adcreative_id = models.IntegerField()
    adplan_id = models.IntegerField()
    adstrategy_id = models.IntegerField()
    landing_name = models.CharField(max_length=32L)
    ip = models.CharField(max_length=32L)
    request = models.CharField(max_length=2048L)
    ua = models.CharField(max_length=1024L)
    referer = models.CharField(max_length=1024L)
    xxxxxxxxtrack = models.CharField(max_length=128L)
    page = models.CharField(max_length=32L)
    monitor_time = models.BigIntegerField()
    original_param = models.CharField(max_length=2048L)
    monitor_type = models.CharField(max_length=32L)
    adsponsor_id = models.IntegerField()
    dt = models.IntegerField()
    hr = models.IntegerField()
    class Meta:
        db_table = 'landing_report_new'

class LandingReportQuery(models.Model):
    id = models.IntegerField(primary_key=True)
    uid = models.IntegerField()
    landing_name = models.CharField(max_length=32L)
    lastupdate = models.IntegerField()
    class Meta:
        db_table = 'landing_report_query'

class LoadSummary(models.Model):
    id = models.IntegerField(primary_key=True)
    load_id = models.BigIntegerField(unique=True, null=True, blank=True)
    load_db = models.CharField(max_length=30L, blank=True)
    load_table = models.CharField(max_length=30L, blank=True)
    load_dt = models.CharField(max_length=8L, blank=True)
    load_hr = models.CharField(max_length=2L, blank=True)
    sponsor_id = models.IntegerField(null=True, blank=True)
    package_name = models.CharField(max_length=255L, blank=True)
    version_name = models.CharField(max_length=30L, blank=True)
    version_code = models.CharField(max_length=30L, blank=True)
    act_begin_time = models.CharField(max_length=10L, blank=True)
    act_end_time = models.CharField(max_length=10L, blank=True)
    act_begin_dt = models.CharField(max_length=8L, blank=True)
    act_end_dt = models.CharField(max_length=8L, blank=True)
    device_id_type = models.CharField(max_length=30L, blank=True)
    is_success = models.IntegerField(null=True, blank=True)
    create_time = models.IntegerField(null=True, blank=True)
    update_time = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = 'load_summary'

class MediaAdConfigInfo(models.Model):
    id = models.IntegerField(primary_key=True, db_column='ID') # Field name made lowercase.
    dt = models.DateField(null=True, blank=True)
    platform = models.CharField(max_length=50L, blank=True)
    core_mediaid = models.IntegerField(null=True, blank=True)
    xxxxxxxx_mediaid = models.IntegerField(null=True, blank=True)
    platform_appid = models.CharField(max_length=150L, blank=True)
    xxxxxxxx_ratio = models.IntegerField(null=True, blank=True)
    baidu_ratio = models.IntegerField(null=True, blank=True)
    mobisage_ratio = models.IntegerField(null=True, blank=True)
    admob_ratio = models.IntegerField(null=True, blank=True)
    adwo_ratio = models.IntegerField(null=True, blank=True)
    inmobi_ratio = models.IntegerField(null=True, blank=True)
    ader_ratio = models.IntegerField(null=True, blank=True)
    adchina_ratio = models.IntegerField(null=True, blank=True)
    publisherid = models.CharField(max_length=50L, db_column='PublisherId', blank=True) # Field name made lowercase.
    placementid = models.CharField(max_length=50L, db_column='PlacementId', blank=True) # Field name made lowercase.
    class Meta:
        db_table = 'media_ad_config_info'

class ReportAdSdkOsDb(models.Model):
    id = models.IntegerField(primary_key=True)
    imp_os = models.IntegerField(null=True, blank=True)
    imp_sdktype = models.IntegerField(null=True, blank=True)
    imp_isv = models.IntegerField(null=True, blank=True)
    adcreativeid = models.IntegerField(null=True, blank=True)
    request = models.IntegerField()
    impression = models.IntegerField()
    eimpression = models.IntegerField()
    click = models.IntegerField()
    lclick = models.IntegerField()
    eclick = models.IntegerField()
    uv = models.IntegerField()
    create_time = models.IntegerField(null=True, blank=True)
    update_time = models.IntegerField(null=True, blank=True)
    dt = models.CharField(max_length=8L, blank=True)
    erequest = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = 'report_ad_sdk_os_db'

class ReportOsSdkDb(models.Model):
    id = models.IntegerField(primary_key=True)
    imp_os = models.IntegerField(null=True, blank=True)
    imp_sdktype = models.IntegerField(null=True, blank=True)
    imp_isv = models.IntegerField(null=True, blank=True)
    request = models.IntegerField()
    impression = models.IntegerField()
    eimpression = models.IntegerField()
    click = models.IntegerField()
    lclick = models.IntegerField()
    eclick = models.IntegerField()
    uv = models.IntegerField()
    create_time = models.IntegerField(null=True, blank=True)
    update_time = models.IntegerField(null=True, blank=True)
    dt = models.CharField(max_length=8L, blank=True)
    erequest = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = 'report_os_sdk_db'

class ReportSdkAppversion(models.Model):
    id = models.IntegerField(primary_key=True)
    imp_appversion = models.CharField(max_length=255L, blank=True)
    imp_isv = models.IntegerField(null=True, blank=True)
    mediaid = models.IntegerField(null=True, blank=True)
    imp_adplacementtype = models.IntegerField(null=True, blank=True)
    request = models.IntegerField()
    impression = models.IntegerField()
    eimpression = models.IntegerField()
    imp_report = models.IntegerField()
    eimp_report = models.IntegerField()
    click = models.IntegerField()
    lclick = models.IntegerField()
    eclick = models.IntegerField()
    uv = models.IntegerField()
    create_time = models.IntegerField(null=True, blank=True)
    update_time = models.IntegerField(null=True, blank=True)
    dt = models.CharField(max_length=8L, blank=True)
    erequest = models.IntegerField(null=True, blank=True)
    os_type = models.IntegerField(null=True, blank=True)
    imp_sdktype = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = 'report_sdk_appversion'

class ReportSdkDb(models.Model):
    id = models.IntegerField(primary_key=True)
    imp_sdkversion = models.CharField(max_length=255L, blank=True)
    imp_sdktype = models.IntegerField(null=True, blank=True)
    imp_isv = models.IntegerField(null=True, blank=True)
    mediaid = models.IntegerField(null=True, blank=True)
    imp_adplacementtype = models.IntegerField(null=True, blank=True)
    request = models.IntegerField()
    impression = models.IntegerField()
    eimpression = models.IntegerField()
    click = models.IntegerField()
    lclick = models.IntegerField()
    eclick = models.IntegerField()
    uv = models.IntegerField()
    create_time = models.IntegerField(null=True, blank=True)
    update_time = models.IntegerField(null=True, blank=True)
    dt = models.CharField(max_length=8L, blank=True)
    erequest = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = 'report_sdk_db'

class UeAder(models.Model):
    use_date = models.DateField()
    time_slot = models.IntegerField(null=True, blank=True)
    creative_id = models.IntegerField(null=True, blank=True)
    package_name = models.CharField(max_length=256L, blank=True)
    action_type = models.CharField(max_length=64L)
    action_count = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = 'ue_ader'

class UeAderDever(models.Model):
    use_date = models.DateField()
    time_slot = models.IntegerField(null=True, blank=True)
    creative_id = models.IntegerField(null=True, blank=True)
    ipb = models.CharField(max_length=32L)
    package_name = models.CharField(max_length=256L, blank=True)
    action_type = models.CharField(max_length=64L)
    action_count = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = 'ue_ader_dever'

class UeDever(models.Model):
    use_date = models.DateField()
    time_slot = models.IntegerField(null=True, blank=True)
    ipb = models.CharField(max_length=32L)
    action_type = models.CharField(max_length=64L)
    action_count = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = 'ue_dever'

